<a href="https://colab.research.google.com/github/davidproton4u/AI-sampleassng/blob/main/Keras_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Submitting all the major imports for the running of the system. (Tensorfolw, Pandas, Numpy, Sklearn, Keras)

import tensorflow as tf
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import Adam
from keras.losses import CategoricalCrossentropy,MeanSquaredError,BinaryCrossentropy
from sklearn.preprocessing import OneHotEncoder

In [ ]:
mnist=tf.keras.datasets.mnist
(x_train,y_train),(x_test,y_test)=mnist.load_data()
x_train,x_test=x_train/255.0,x_test/255.0
model=tf.keras.models.Sequential([tf.keras.layers.Flatten(input_shape=(28, 28)),tf.keras.layers.Dense(128,activation='relu'),tf.keras.layers.Dropout(0,2),tf.keras.layers.Dense(10)])
predictions=model(x_train[:1]).numpy()
predictions

11490434/11490434 [==============================] - 0s 0us/step


array([[-0.54272586, -0.22611949, -0.1862148 , -0.07857635,  0.29943284,
        -0.01178459, -0.52158827,  0.12814789, -0.28555933,  0.03022444]],
      dtype=float32)

In [ ]:
#Using the TF and Softmax commands
tf.nn.softmax(predictions).numpy()

array([[0.06469383, 0.08878984, 0.09240461, 0.10290594, 0.15017849,
        0.11001394, 0.06607586, 0.1265376 , 0.08366597, 0.11473397]],
      dtype=float32)

In [ ]:
#Calc. Loss
loss_fn=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True )

In [ ]:
loss_fn(y_train[:1],predictions).numpy()

2.207148

In [ ]:
model.compile(optimizer='adam',loss=loss_fn, metrics=['accuracy'])

In [ ]:
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2563 - accuracy: 0.9269
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1152 - accuracy: 0.9653
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0794 - accuracy: 0.9762
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0580 - accuracy: 0.9820
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0451 - accuracy: 0.9855


In [ ]:
model.evaluate(x_test,y_test,verbose=2)

313/313 - 1s - loss: 0.0764 - accuracy: 0.9769 - 622ms/epoch - 2ms/step


[0.07640384882688522, 0.9768999814987183]

In [ ]:
#Loading the dataset - Iris.csv
df = pd.read_csv("Iris.csv")

#Condition for the extraction from data frame
df = df[df["species"]!="Iris-setosa"]
y = df["species"]
X = df.loc[:, ["sepal_length", "sepal_width", "petal_length", "petal_width"]]

# NumPy
X = np.array(X)
y = np.array(y)

# Converting the label in the dataset to numbers
y[y == "Iris-versicolor"] = 0
y[y == "Iris-virginica"] = 1
y = y.astype(np.int64)[:, np.newaxis]

#Spliting into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
enc = OneHotEncoder(handle_unknown='ignore', sparse=False)
y_train_one_hot = enc.fit_transform(y_train)
y_test_one_hot = enc.transform(y_test)

/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [ ]:
def classification_evaluation(x_train,y_train,x_test,crossentropy,verbose,output_units):
  model=Sequential()
  model.add(Dense(50,activation=tf.nn.relu))
  model.add(Dense(100,activation=tf.nn.relu))
  model.add(Dense(output_units,activation=tf.nn.sigmoid))
  model.compile(optimizer=Adam(learning_rate=0.001),loss=crossentropy(),metrics=["accuracy"])
  model.fit(x_train,y_train,shuffle=True,batch_size=10,epochs=300,verbose=verbose)
  score=model.evaluate(x_train,y_train,verbose=0)
  print('Train loss:', score[0])
  print('Train accuracy:',score[1])
  pred_proba=model.predict(x_test,batch_size=10)[:,0]
  rounded_preds=np.where(pred_proba> 0.5 , 1, 0)
  print(rounded_preds)

In [ ]:
classification_evaluation(X_train,y_train,X_test,BinaryCrossentropy,0,1)

Train loss: 0.02058783918619156
Train accuracy: 1.0
2/2 [==============================] - 0s 5ms/step
[0 1 0 1 1 1 0 1 1 1 1 1 1 0 0 0 1 0 1 0]


In [ ]:
#Loading the dataset from the Iris.csv frame
df = pd.read_csv("Iris.csv")

#Condition extraction from data frame
y = df["species"]
X = df.loc[:, ["sepal_length", "sepal_width", "petal_length", "petal_width"]]

# Numpy declarations
X = np.array(X)
y = np.array(y)

# Converting the labels in the dataset to numbers
y[y == "Iris-setosa"] = 0
y[y == "Iris-versicolor"] = 1
y[y == "Iris-virginica"] = 2
y = y.astype(np.int64)[:, np.newaxis]

#Spliting into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
enc = OneHotEncoder(handle_unknown='ignore', sparse=False)
y_train_one_hot = enc.fit_transform(y_train)
y_test_one_hot = enc.transform(y_test)

/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [ ]:
model = Sequential()
model.add(Dense(50, activation=tf.nn.relu))
model.add(Dense(100, activation=tf.nn.relu))
model.add(Dense(3, activation=tf.nn.softmax))
model.compile(optimizer=Adam(learning_rate=0.001), loss=CategoricalCrossentropy(), metrics=["accuracy"])
model.fit(X_train, y_train_one_hot, shuffle=True, batch_size=10, epochs=300, verbose=0)
score = model.evaluate(X_train, y_train_one_hot, verbose=0)
print('Train loss:', score[0])
print('Train accuracy:', score[1])
pred_proba = model.predict(X_test,batch_size=10)
pred = np.argmax(pred_proba, 1)
print(pred)

Train loss: 0.057767536491155624
Train accuracy: 0.9750000238418579
3/3 [==============================] - 0s 5ms/step
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]


In [ ]:
house_df=pd.read_csv("ghana.csv")
house_df.head()

Id  House Size (sqft)  Number of Bedrooms      Location  House Price (GHS)
0   1               1000                   2        Adenta             280000
1   2               1500                   3    East Legon             450000
2   3               2000                   4      Achimota             550000
3   4               2200                   3  Spintex Road             600000
4   5               2500                   4   Cantonments             750000

In [ ]:
h_x=house_df[['Location','House Size (sqft)', 'Number of Bedrooms']]
h_y=house_df['House Price (GHS)']

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(h_x['Location'])
h_x['Location'] = le.transform(h_x['Location'])

<ipython-input-15-74b787ca5ec5>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  h_x['Location'] = le.transform(h_x['Location'])


In [ ]:
h_x.shape,h_y.shape

((92, 3), (92,))

In [ ]:
h_x_train,h_x_test,h_y_train,h_y_test=train_test_split(h_x,h_y,train_size=0.2,random_state=0)

In [ ]:
model=Sequential()
model.add(Dense(50,activation=tf.nn.relu))
model.add(Dense(100,activation=tf.nn.relu))
model.add(Dense(1,activation=tf.keras.activations.linear))
model.compile(optimizer=Adam(learning_rate=0.001),loss=MeanSquaredError(),metrics=["mse"])
model.fit(h_x_train,h_y_train,shuffle=True,batch_size=10,epochs=20,verbose=0)
score=model.evaluate(h_x_train,h_y_train,verbose=0)
print('Loss:', score[0])
print('MSE:',score[1])
pred=model.predict(h_x_test,batch_size=10)
print(pred.ravel())
print(h_y_test.ravel())

Loss: 194117673943040.0
MSE: 194117673943040.0
8/8 [==============================] - 0s 2ms/step
[ 1678.2147   2013.8617   5034.4585   2182.6265   1426.6073   1008.17426
  6544.653    9228.921    9899.928    7886.8247   4027.212    3356.5269
  1594.9534   9732.515    3524.739    7048.3613   3776.4033  11074.688
  5033.9272   1510.6853   3357.097    5537.5405   2937.295    3691.8887
  9397.02     8894.013    5872.863    9061.732   10068.408   10570.997
  1846.9978   8390.381   10236.072    1007.699    3272.3538   5705.6396
  5370.352   11745.657    6712.485    6377.029    2097.9397   1929.8785
  2685.1555   3188.1982   2853.3115   2517.323   10739.78     4531.3774
   839.3527   2182.1514   1174.8483   4866.7954   1008.17426  2349.7937
  1426.8923   5202.711    1510.7804   1678.9751   6879.578    6041.135
  8725.2295   1259.4015   1846.9025   9564.243    1594.9534   7551.3296
  3524.549    1343.6312   4699.0015  11410.088   11578.281    8054.239
  4027.6692  10907.537  ]
[  550000   680

In [ ]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()
x_train=x_train[0:6000,:]
y_train=y_train[0:6000]
x_test=x_test[0:6000,:]
y_test=y_test[0:6000]
x_train.shape

(6000, 28, 28)

In [ ]:
x_train=x_train.reshape(-1, 784)
x_test=x_test.reshape(-1,784)

In [ ]:
x_train=x_train.astype(np.float64)
x_test=x_test.astype(np.float64)
x_train/=255
x_test/=255

In [ ]:
m_x_train,m_x_test,m_y_train,m_y_test=train_test_split(x_train,y_train,test_size=0.2,random_state=0)

In [ ]:
enc=OneHotEncoder(handle_unknown='ignore',sparse_output=False)
y_train_one_hot=enc.fit_transform(m_y_train[:,np.newaxis])
y_test_one_hot=enc.transform(m_y_test[:,np.newaxis])

In [ ]:
model=Sequential()
model.add(Dense(50,activation=tf.nn.relu))
model.add(Dense(100,activation=tf.nn.relu))
model.add(Dense(10,activation=tf.nn.softmax))
model.compile(optimizer=Adam(learning_rate=0.001),loss=CategoricalCrossentropy(),metrics=["accuracy"])
model.fit(m_x_train,y_train_one_hot,shuffle=True,batch_size=10,epochs=300,verbose=0)
score=model.evaluate(m_x_train,y_train_one_hot,verbose=0)
print('Train loss:', score[0])
print('Train accuracy:',score[1])
pred_proba=model.predict(m_x_test,batch_size=10)
pred=np.argmax(pred_proba,1)
print(pred)

Train loss: 4.124170300201513e-05
Train accuracy: 1.0
120/120 [==============================] - 0s 1ms/step
[9 9 4 ... 7 2 4]
