<a href="https://colab.research.google.com/github/davidproton4u/AI-sampleassng/blob/main/Matrix_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix Assignment

In [2]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

ab_ndarray = a_ndarray @ b_ndarray 

print(ab_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


#Problem 3 - Implementation of Calculation of a certain element

In [3]:
sum_of_ab_ndarray = (a_ndarray[1][0]*b_ndarray[0][1]+(a_ndarray[1][1]*b_ndarray[1][1])+(a_ndarray[1][2]*b_ndarray[2][1]))
print(sum_of_ab_ndarray)

52


Problem 4 - Creating a function that performs a Matrix Multiplication

In [4]:
def product_of_matrix(a, b):
    ab_ndarray = np.empty([3,3])
    for row in range(a.shape[0]):
        for column in range(b.shape[1]):
            ab_ndarray[row][column] = sum(a[row, :]*b[:, column])
    return ab_ndarray
print(product_of_matrix(a_ndarray, b_ndarray))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


#Problem 5 - Judge the input whose calculation is not defined

In [6]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
if(d_ndarray.shape[0]==e_ndarray.shape[1]):
    print(product_of_matrix(d_ndarray, e_ndarray))
else:
          print("Hello Programmer, there is a problem with the Size f the Matrices, which may result in incorrect calculations. Try again Later")


Hello Programmer, there is a problem with the Size f the Matrices, which may result in incorrect calculations. Try again Later


#Problem 6 - Transposition

In [7]:
f_ndarray = d_ndarray.T
print(product_of_matrix(f_ndarray, e_ndarray))

[[ 33. -28.   9.]
 [-48.  41.  -6.]
 [  9.  -6.  45.]]
